package com.github.thesilentpro.hangarapi.response.implementation.permission;

public enum Permission {

    VIEW_PUBLIC_INFO,
    EDIT_OWN_USER_SETTINGS,
    EDIT_API_KEYS,
    EDIT_SUBJECT_SETTINGS,
    MANAGE_SUBJECT_MEMBERS,
    IS_SUBJECT_OWNER,
    IS_SUBJECT_MEMBER,
    CREATE_PROJECT,
    EDIT_PAGE,
    DELETE_PROJECT,
    CREATE_VERSION,
    EDIT_VERSION,
    DELETE_VERSION,
    EDIT_CHANNELS,
    CREATE_ORGANIZATION,
    DELETE_ORGANIZATION,
    POST_AS_ORGANIZATION,
    MOD_NOTES_AND_FLAGS,
    SEE_HIDDEN,
    IS_STAFF,
    REVIEWER,
    VIEW_HEALTH,
    VIEW_IP,
    VIEW_STATS,
    VIEW_LOGS,
    MANUAL_VALUE_CHANGES,
    RESTORE_VERSION,
    RESTORE_PROJECT,
    HARD_DELETE_PROJECT,
    HARD_DELETE_VERSION,
    EDIT_ALL_USER_SETTINGS;

}
